version: '3'
services:
  app:
    build: './app'
    ports:
      - "3000:3000"
    networks:
      - net
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24
